{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alexandria.name" . }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ required "database.url is required" .Values.database.url | quote }}
  object-access-key: {{ .Values.objectStore.accessKey | quote }}
  object-secret-key: {{ .Values.objectStore.secretKey | quote }}
{{- end }}
