#!/bin/sh
# Install or upgrade Aragonite Alexandria Server with Docker Compose (or
# Podman Compose) on one host. Safe to re-run: it keeps an existing .env,
# rebuilds the image, and lets the one-shot migrate/bootstrap services bring
# the database up to date before the server starts.
set -eu
cd "$(dirname "$0")"

compose() {
	if [ -n "${COMPOSE:-}" ]; then $COMPOSE "$@"
	elif docker compose version >/dev/null 2>&1; then docker compose "$@"
	elif podman compose version >/dev/null 2>&1; then podman compose "$@"
	elif command -v docker-compose >/dev/null 2>&1; then docker-compose "$@"
	else echo "Install Docker Compose v2 or Podman Compose first (or set COMPOSE)." >&2; exit 1
	fi
}
secret() { od -An -N"$1" -tx1 /dev/urandom | tr -d ' \n'; }
ask() { printf '%s' "$1" >&2; read -r REPLY; printf '%s' "${REPLY:-$2}"; }

first_run=false
if [ ! -f .env ]; then
	first_run=true
	url=$(ask "Public address of this server, as users will type it (https://alexandria.example.com): " "")
	case "$url" in
	https://*|http://localhost*|http://127.0.0.1*) ;;
	*) echo "The address must start with https:// (put the server behind your TLS reverse proxy)." >&2; exit 1 ;;
	esac
	admin=$(ask "Administrator username [admin]: " "admin")
	umask 077
	cat > .env <<ENV
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%MZ). Keep this file private.
ALEXANDRIA_PUBLIC_URL=${url%/}
ALEXANDRIA_POSTGRES_PASSWORD=$(secret 24)
ALEXANDRIA_RUNTIME_PASSWORD=$(secret 24)
ALEXANDRIA_OBJECT_ACCESS_KEY=alexandria$(secret 8)
ALEXANDRIA_OBJECT_SECRET_KEY=$(secret 32)
ALEXANDRIA_ADMIN_USERNAME=$admin
ALEXANDRIA_MAIN_PORT=18443
ALEXANDRIA_SPC_PORT=18089
ALEXANDRIA_MAX_CONNECTIONS=16
ALEXANDRIA_BACKUP_DIR=./backups

# Optional handwriting recognition (see docs/deployment-compose.md):
#ALEXANDRIA_OCR_URL=https://api.anthropic.com
#ALEXANDRIA_OCR_API_KEY=
#ALEXANDRIA_OCR_MODEL=
#ALEXANDRIA_OCR_FORMAT=anthropic
# Optional search by meaning, with an Ollama server:
#ALEXANDRIA_EMBED_URL=http://ollama.example:11434
#ALEXANDRIA_EMBED_MODEL=nomic-embed-text:v1.5
ENV
	echo "Wrote .env with new random secrets."
fi

echo "Building the server image (this takes a few minutes the first time)..."
compose build alexandria
echo "Starting the server..."
# Recreate every container so all of them run the image just built (some
# Compose implementations otherwise keep a container on the previous image).
compose up -d --force-recreate

port=$(sed -n 's/^ALEXANDRIA_MAIN_PORT=//p' .env)
port=${port:-18443}
printf 'Waiting for the server to become ready'
i=0
until wget -q -O /dev/null "http://127.0.0.1:$port/readyz" 2>/dev/null || curl -fs -o /dev/null "http://127.0.0.1:$port/readyz" 2>/dev/null; do
	i=$((i + 1))
	if [ "$i" -gt 120 ]; then
		echo; echo "The server did not become ready. See the logs with: docker compose logs alexandria (or podman compose logs alexandria)." >&2
		exit 1
	fi
	printf '.'; sleep 2
done
echo " ready."

if $first_run; then
	admin=$(sed -n 's/^ALEXANDRIA_ADMIN_USERNAME=//p' .env)
	while :; do
		printf 'Password for %s (at least 12 characters): ' "$admin" >&2
		stty -echo 2>/dev/null || true; read -r pw1; stty echo 2>/dev/null || true; echo >&2
		printf 'Repeat it: ' >&2
		stty -echo 2>/dev/null || true; read -r pw2; stty echo 2>/dev/null || true; echo >&2
		if [ "$pw1" = "$pw2" ] && [ "${#pw1}" -ge 12 ]; then break; fi
		echo "The passwords differ or are shorter than 12 characters. Try again." >&2
	done
	printf '%s' "$pw1" | compose --profile setup run --rm --no-deps -T seed-admin
	unset pw1 pw2
fi

url=$(sed -n 's/^ALEXANDRIA_PUBLIC_URL=//p' .env)
cat <<DONE

Alexandria Server is running on 127.0.0.1:$port (plain HTTP, local only).
Point your TLS reverse proxy at it so it answers at $url, for example with Caddy:

  ${url#https://} {
      reverse_proxy 127.0.0.1:$port {
          flush_interval -1
          transport http {
              read_timeout 20m
              write_timeout 20m
          }
      }
      request_body {
          max_size 32MB
      }
  }

Then sign in at $url, and on each tablet open Alexandria Settings > Sync >
Connect This Device, with that address and the administrator account. See
docs/deployment-compose.md for nginx, backups and upgrades.
DONE
